package common

var CommonRMMs = []string{
	// A
	"Action1",
	"Action1RMM",
	"Action 1",
	"Action 1 RMM",
	"AeroAdmin",
	"Aero Admin",
	"Alpemix",
	"AMMYY",
	"AMMYY Admin",
	"AMMYYAdmin",
	"Atera",
	"AteraAgent",
	"Atera Agent",
	"AnyDesk",
	"Any Desk",
	"AnyViewer",
	"Any Viewer",
	"AnyPlace Control",
	"AnyPlaceControl",
	"AweSun",
	"Awe Sun",
	"Auvik",

	// B
	"BeamYourScreen",
	"Beam Your Screen",
	"BeAnywhere",
	"Be Anywhere",
	"Bitvise",
	"Bitvise SSH",
	"BitviseSSH",
	"Bluetrait",
	"Bluetrait Agent",
	"BluetraitAgent",
	"Bomgar",
	"BeyondTrust",
	"Beyond Trust",

	// C
	"Chrome Remote Desktop",
	"ChromeRemoteDesktop",
	"Cloudberry",
	"CloudBerry",
	"Cloud Berry",
	"Comodo One",
	"ComodoOne",
	"Comodo RMM",
	"ComodoRMM",
	"ConnectWise",
	"ConnectWise Control",
	"ConnectWiseControl",
	"Connect Wise",
	"ScreenConnect",
	"Screen Connect",
	"CrossLoop",
	"Cross Loop",

	// D
	"Dameware",
	"Dameware Remote",
	"DamewareRemote",
	"Datto RMM",
	"DattoRMM",
	"Datto",
	"DesktopCentral",
	"Desktop Central",
	"Deskroll",
	"Desk Roll",
	"Distant Desktop",
	"DistantDesktop",
	"Domotz",
	"DWAgent",
	"DW Agent",
	"DWService",
	"DW Service",

	// E
	"Ehorus",
	"Ericom Connect",
	"EricomConnect",

	// F
	"FastViewer",
	"Fast Viewer",
	"FixMeIT",
	"Fix Me IT",
	"FixMeIt",
	"FleetDeck",
	"Fleet Deck",

	// G
	"GetScreen",
	"Get Screen",
	"GoTo",
	"GoToAssist",
	"GoTo Assist",
	"GoToMyPC",
	"GoTo MyPC",
	"GoToRemote",
	"GoTo Remote",
	"Goverlan",
	"GovReach",
	"Gov Reach",

	// H
	"HelpU",
	"Help U",

	// I
	"ISL Online",
	"ISLOnline",
	"ISL Light",
	"ISLLight",
	"Impero",
	"Impero Connect",
	"ImperoConnect",
	"Insync",
	"InstantHousecall",
	"Instant Housecall",
	"Iperius",
	"Iperius Remote",
	"IperiusRemote",
	"iTarian",
	"Ivanti",
	"Ivanti Neurons",
	"IvantiNeurons",

	// J
	"JumpCloud",
	"Jump Cloud",
	"JumpDesktop",
	"Jump Desktop",

	// K
	"Kabuto",
	"Kaseya",
	"Kaseya VSA",
	"KaseyaVSA",
	"Kickidler",

	// L
	"LANDesk",
	"LAN Desk",
	"Ivanti EPM",
	"IvantiEPM",
	"Laplink",
	"Laplink Everywhere",
	"LaplinkEverywhere",
	"Level",
	"Level RMM",
	"LevelRMM",
	"LiteManager",
	"Lite Manager",
	"LogMeIn",
	"Log Me In",
	"LogMeIn Rescue",
	"LogMeInRescue",

	// M
	"ManageEngine",
	"Manage Engine",
	"ManageEngine RMM",
	"ManageEngineRMM",
	"MeshCentral",
	"Mesh Central",
	"Mikogo",
	"mRemoteNG",
	"mRemote NG",

	// N
	"N-able",
	"Nable",
	"N-able RMM",
	"NableRMM",
	"N-Central",
	"NCentral",
	"NetOp",
	"Net Op",
	"NetSupport",
	"Net Support",
	"NetSupport Manager",
	"NetSupportManager",
	"NetViewer",
	"Net Viewer",
	"Neturo",
	"NinjaOne",
	"Ninja One",
	"NinjaRMM",
	"Ninja RMM",
	"NoMachine",
	"No Machine",

	// O
	"Oray",
	"Oray Sunlogin",
	"OraySunlogin",

	// P
	"PAExec",
	"Parallels",
	"Parallels RAS",
	"ParallelsRAS",
	"PCAnywhere",
	"PC Anywhere",
	"PCMonitor",
	"PC Monitor",
	"PCVisit",
	"PC Visit",
	"PDQ Connect",
	"PDQConnect",
	"Pilixo",
	"PocketCloud",
	"Pocket Cloud",
	"Pulseway",
	"PsExec",

	// R
	"Radmin",
	"Rapid7",
	"Rapid7 Insight",
	"Rapid7Insight",
	"RealVNC",
	"Real VNC",
	"Remote Utilities",
	"RemoteUtilities",
	"RemotePC",
	"Remote PC",
	"RemoteCall",
	"Remote Call",
	"RemoteView",
	"Remote View",
	"Remote.It",
	"RemoteIt",
	"Remcos",
	"Remobo",
	"Rport",
	"RPort",
	"RustDesk",
	"Rust Desk",
	"RDP",
	"Remote Desktop",
	"RemoteDesktop",

	// S
	"Screenleap",
	"Screen Leap",
	"ScreenMeet",
	"Screen Meet",
	"Seetrol",
	"Senso",
	"ServerEye",
	"Server Eye",
	"ShowMyPC",
	"Show My PC",
	"SimpleHelp",
	"Simple Help",
	"Site24x7",
	"Site 24x7",
	"SolarWinds",
	"Solar Winds",
	"SolarWinds RMM",
	"SolarWindsRMM",
	"SolarWinds Dameware",
	"SolarWindsDameware",
	"Sorillus",
	"Splashtop",
	"Splash Top",
	"Splashtop SOS",
	"SplashtopSOS",
	"Supremo",
	"Supremo Remote",
	"SupremoRemote",
	"Syncro",
	"SyncroMSP",
	"Syncro MSP",
	"SysAid",
	"Sys Aid",

	// T
	"TacticalRMM",
	"Tactical RMM",
	"Tailscale",
	"Tail Scale",
	"Tanium",
	"TeamViewer",
	"Team Viewer",
	"TightVNC",
	"Tight VNC",
	"ToDesk",
	"To Desk",
	"TurboMeeting",
	"Turbo Meeting",
	"TigerVNC",
	"Tiger VNC",

	// U
	"UltraVNC",
	"Ultra VNC",
	"UltraViewer",
	"Ultra Viewer",

	// V
	"VNC",
	"VNC Connect",
	"VNCConnect",
	"VNC Server",
	"VNCServer",
	"VNC Viewer",
	"VNCViewer",

	// W
	"Weezo",
	"WinSCP",
	"Win SCP",

	// X
	"Xeox",
	"Xpra",

	// Z
	"Zabbix",
	"ZeroTier",
	"Zero Tier",
	"Zoho",
	"Zoho Assist",
	"ZohoAssist",
	"ZOC",
	"ZOC Terminal",
	"ZOCTerminal",

	// Additional variants and abbreviations
	"RMM",
	"Remote Management",
	"RemoteManagement",
	"Remote Monitoring",
	"RemoteMonitoring",
	"Remote Support",
	"RemoteSupport",
	"Remote Access",
	"RemoteAccess",
	"Remote Control",
	"RemoteControl",
	"Remote Admin",
	"RemoteAdmin",
	"Remote Administrator",
	"RemoteAdministrator",

	// MSP Tools
	"MSP360",
	"MSP 360",
	"Continuum",
	"Autotask",
	"Auto Task",
	"Kaseya BMS",
	"KaseyaBMS",
	"Connectwise Manage",
	"ConnectwiseManage",
	"Connectwise Automate",
	"ConnectwiseAutomate",

	// Cloud-based
	"AWS Systems Manager",
	"AWSSystemsManager",
	"Azure Arc",
	"AzureArc",
	"Google Remote Desktop",
	"GoogleRemoteDesktop",

	// Open Source
	"Apache Guacamole",
	"ApacheGuacamole",
	"Remmina",
	"FreeRDP",
	"Free RDP",
	"xRDP",
	"OpenSSH",
	"Open SSH",

	// Additional Commercial
	"AeroAdmin",
	"Aero Admin",
	"Alpemix Service",
	"AlpemixService",
	"BeamYourScreen",
	"Beam Your Screen",
	"Cloudflared",
	"Cloudflare Tunnel",
	"CloudflareTunnel",
	"CrossTec",
	"Cross Tec",
	"CrossTec Remote Control",
	"CrossTecRemoteControl",
	"DeskRoll",
	"Desk Roll",
	"Electric",
	"Electric RMM",
	"ElectricRMM",
	"Encapto",
	"EricomConnect",
	"Ericom Connect",
	"ESet RMM",
	"ESetRMM",
	"ESET Remote Administrator",
	"ESETRemoteAdministrator",
	"GetGo",
	"Get Go",
	"GoToHTTP",
	"GoTo HTTP",
	"Goverreach",
	"HelpMe",
	"Help Me",
	"ImInTouch",
	"I'm InTouch",
	"IntelliAdmin",
	"Intelli Admin",
	"ITSM",
	"Manage Engine ITSM",
	"ManageEngineITSM",
	"Kabuto",
	"KHelpDesk",
	"K Help Desk",
	"Laplink Gold",
	"LaplinkGold",
	"LogicNow",
	"Logic Now",
	"MaxFocus",
	"Max Focus",
	"MioNet",
	"Mio Net",
	"MyGreenPC",
	"My Green PC",
	"Naverisk",
	"Naverisk RMM",
	"NaveriskRMM",
	"Netop Remote Control",
	"NetopRemoteControl",
	"Neturo",
	"NTRSupport",
	"NTR Support",
	"OCS Inventory",
	"OCSInventory",
	"OptiTune",
	"Opti Tune",
	"Panorama9",
	"Panorama 9",
	"Parsec",
	"PocketController",
	"Pocket Controller",
	"Radmin VPN",
	"RadminVPN",
	"Remobo",
	"RemotePass",
	"Remote Pass",
	"RemoteWorkforce",
	"Remote Workforce",
	"RepairShopr",
	"Repair Shopr",
	"RocketRemoteDesktop",
	"Rocket Remote Desktop",
	"RoyalTS",
	"Royal TS",
	"RPort",
	"R Port",
	"RuDesktop",
	"Ru Desktop",
	"Servably",
	"Simple Gateway",
	"SimpleGateway",
	"SmartFTP",
	"Smart FTP",
	"SuperOps",
	"Super Ops",
	"SuperOps.ai",
	"SuperOpsAI",
	"SupportTool",
	"Support Tool",
	"SyncThru",
	"Sync Thru",
	"SyncTrayzor",
	"Sync Trayzor",
	"TeamTaskManager",
	"Team Task Manager",
	"TechinLine",
	"Techin Line",
	"Total Software Deployment",
	"TotalSoftwareDeployment",
	"Webex",
	"Webex PCNow",
	"WebexPCNow",
	"WiseRMM",
	"Wise RMM",
	"Xpra",
	"X Pra",
	"XSight",
	"X Sight",
	"Yandex",
	"Yandex Remote Desktop",
	"YandexRemoteDesktop",
}
